name: ci

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [lint, test]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
        if: ${{ !steps.yarn-cache.outputs.cache-hit }}
      - run: yarn ${{ matrix.task }}
